#!/usr/bin/env python3
#!-*- coding : utf-8 -*-

import sys

try:

    if len(sys.argv) !=4:
        raise ValueError("Eksik Arguman")
        
    print("Geçirilen Argumanlar:", sys.argv)
    with open(sys.argv[3],'r') as f:
        content = f.read().split('\n')
        for i,j in enumerate(content):
            if sys.argv[1] in j:
                content[i] = content[i].replace(sys.argv[1], sys.argv[2])
            
         
    for i in content:
        print(i)
except ValueError:
    print('Kullanım', end=' -> ')
    print('"replace [Kaynak] [Hedef] [Dosya]"')
